name: Deploy project ğŸ™Œ
on:
  push:
    branches: [main]
jobs:
  build-project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    name: Node ${{ matrix.node }} sample
    steps:
      # Clone this repo
      - name: Checkout repo ğŸ”
        uses: actions/checkout@v3

      # Install Node.js
      - name: Staring Node.js ${{ matrix.node }} ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # Install dependencies
      - name: Install modules ğŸ”§
        run: npm install

      # Run tests
      - name: Build project ğŸ‘·
        run: npm run build

      # Deploy project
      - name: Deploy project ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
