name: Lint Tests ğŸ™Œ
on:
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [16, 18]
    name: Test lint and build project
    steps:
      # Clone this repo
      - name: Checkout repo ğŸ”
        uses: actions/checkout@v3

      # Install Node.js
      - name: Staring Node.js ${{ matrix.node }} ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # Install dependencies
      - name: Install modules ğŸ”§
        run: npm ci

      # Run tests
      - name: test eslint ğŸ”¨
        run: npm run test-eslint
      - name: test prettier ğŸ”¨
        run: npm run test-prettier

      # Build tests
      - name: test build project ğŸ”¨
        run: npm run build
